### ISSUE TITLE
hwo to get log files of gopro 9, by special cable or wifi?

### ISSUE THREAD

**Issue by chuangaf** [hypoxic/GoPro-Research#4]

**Comment by hypoxic** [comment]
There is an exploit I'm using to get access to these logs, but I rather not release it into public domain. A special debug cable can be used, or you can hardware onto the test pads if you have opened up your camera. The debug cable requires a gopro programmed atsha204 and a tweaked Cypress USB-PD chip. It seems they're building up changing the log levels via bluetooth, but as far as I can tell, this isn't operationally yet. The problem is there isn't a method to enable the RTOS logs to file externally so you have to do that from the console. 
You can also patch the rtos to enable CDC USB by default, but I would not recommend that. The easiest way is to patch the linux bootup sequence to call a script on your card and enable telnet. There is not a method to unbrick these cameras as far as I can tell so be careful!
